### ISSUE TITLE
[Bug]: 0.8.2 is default download instead of 0.8.5

### ISSUE THREAD

**Issue by illwieckz** [snapcrafters/xonotic#14]
### What happened?

The 0.8.2 version is flagged as stable and the 0.8.5 is flagged as edge so the default download is 0.8.2.

### What should have happened?

The 0.8.5 version should be flagged as stable and be the default download.

**Comment by illwieckz** [comment]
It's also good to know the 0.8.2 version isn't compatible with the actual servers that are all running 0.8.5, so proposing 0.8.2 by default just offers a very bad xonotic and snap experience.

**Comment by tobhe** [comment]
I believe this one has been resolved too

**Comment by lucyllewy** [comment]
this has been superseded, so I'm closing the issue

**Comment by illwieckz** [comment]
Thank you for taking care of that issue. Unfortunately this looks to be only partially fixed.

If I use GNOME Software, it proposes me Xonotic 0.8.6 as stable as expected.

But if I use the website ( https://snapcraft.io/xonotic ), it still proposes me the very obsolete Xonotic 0.8.2 as stable and default, while listing Xonotic 0.8.6 as edge and non-default.

**Comment by tobhe** [comment]
The website just takes a while to update because it caches quite aggressively. Try `https://snapcraft.io/xonotic?cache-buster=9001` and you'll see that it shows the right version. I have raised the issue with the responsible team.
